out_dir : './experiments/synthetic_experiments/20240701/'
dimensions : [3, 6, 8]
num_objectives : 2
num_samples : 3
noise_variance : 0.01
factor_lengthscale : 2
gamma : 0.3
gp_hypers: 
    outputscale: 1.
n_max: 5
