out_dir : './experiments/synthetic_experiments/test_experiment/'
dimensions : [3, 6]
num_objectives : 5
num_samples : 10
noise_variance : 0.01
factor_lengthscale : 2
gamma : 0.3
gp_hypers: 
    outputscale: 1.
n_max: 5
