out_dir : './experiments/synthetic_experiments/20240703/'
dimensions : [40, 80, 120]
num_objectives : 3
num_samples : 1000
noise_variance : 0.01
factor_lengthscale : 2
gamma : 0.3
gp_hypers: 
    outputscale: 1.
n_max: 15
